name: "Build Libraries"
inputs:
  BRANCH:
    description: 'Branch to build'
    default: 'master'
    required: true
    type: string
  SOLUTIONNAME:
    required: true
    type: string
  PROJECTS:
    required: true
    type: string
  NUGET_API_KEY:
    required: true
runs:
  using: "composite"
  steps: 
    - name: Make Dynamic Build Yaml Script
      shell: cmd
      run: |
        mkdir .github\actions\dynamic_build
        SET action=.github/actions/dynamic_build/action.yaml
        SET Projects=${{ inputs.PROJECTS }}
        SET KeyText=${
        SET KeyText=%KeyText%{
        SET KeyText=%KeyText% secrets.NUGET_API_KEY
        SET KeyText=%KeyText% }
        SET KeyText=%KeyText%}
        
        echo name: Build - ${{ inputs.SOLUTIONNAME }}  > %action%
        echo inputs:>>  %action%
        echo   BRANCH:>>  %action%
        echo     description: 'Branch to build'>>  %action%
        echo     default: 'master'>>  %action%
        echo     required: true>>  %action%
        echo     type: string>>  %action%
        echo   NUGET_API_KEY:>>  %action%
        echo     required: true>>  %action%
        echo runs:>>  %action%
        echo   using: "composite">>  %action%
        echo   steps:>>  %action%

        for %%a in (%Project%) do (
            for /F "tokens=1-2 delims=#" %%B in ("%%a") do (
        echo     - name: "Build %%B">>  %action%
                if NOT "%%B%%C" == "%%C%%B" (
        echo ***************** echo Inserting %%B - %%C echo *****************
        echo       uses: SafetyNationalPublic/devops_sn-common/actions/build_workflow_library@main>>  %action%
        echo       with:>>  %action%
        echo         BRANCH: ${{ inputs.BRANCH }}>>  %action%
        echo         PROJECTPATH: ^"%%B\\%%C^">>  %action%
        echo         PROJECTFILENAME: "%%B">>  %action%
        echo         NUGET_API_KEY: %KeyText%>>  %action%
                ) else (
        echo ***************** echo Inserting %%B only echo *****************
        echo       uses: SafetyNationalPublic/devops_sn-common/actions/build_workflow_library_if_exists@main>>  %action%
        echo       with:>>  %action%
        echo         BRANCH: ${{ inputs.BRANCH }}>>  %action%
        echo         PROJECT: ^"%%B^">>  %action%
        echo         NUGET_API_KEY: %KeyText%>>  %action%
                )
            )
        )
        echo Build File Located at:  %action%
        type .github\actions\dynamic_build\action.yaml
