name: "Build Libraries"
inputs:
  BRANCH:
    description: 'Branch to build'
    default: 'master'
    required: true
    type: string
  BUILDFILE:
    required: true
    type: string
  SOLUTIONNAME:
    required: true
    type: string
  PROJECTS:
    required: true
    type: string

runs:
  using: "composite"
  steps: 
    - name: Make Dynamic Build Yaml Script
      shell: cmd
      run: |
        echo name: Build - {{ "{{ inputs.SOLUTIONNAME }}" }}  > {{ "{{ inputs.BUILDFILE }}" }}
        echo on:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo   workflow_dispatch:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo     inputs:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo       BRANCH:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo         description: 'Branch to build'>> {{ "{{ inputs.BUILDFILE }}" }}
        echo         default: 'master'>> {{ "{{ inputs.BUILDFILE }}" }}
        echo         required: true>> {{ "{{ inputs.BUILDFILE }}" }}
        echo defaults:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo   run:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo     shell: cmd>> {{ "{{ inputs.BUILDFILE }}" }}
        echo jobs:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo   Build_Libraries:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo     name: "Build Libraries">> {{ "{{ inputs.BUILDFILE }}" }}
        echo     runs-on: SNGithubRunner>> {{ "{{ inputs.BUILDFILE }}" }}
        echo     steps:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo       - name: "Call Checkout">> {{ "{{ inputs.BUILDFILE }}" }}
        echo         uses: actions/checkout@v3>> {{ "{{ inputs.BUILDFILE }}" }}
        echo         with:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo           ref: ${{ github.event.inputs.BRANCH }}>> {{ "{{ inputs.BUILDFILE }}" }}

        for %%a in ({{ "{{ inputs.PROJECTS }}" }}) do (
            for /F "tokens=1-2 delims=#" %%B in ("%%a") do (
        echo       - name: "Build %%B">> {{ "{{ inputs.BUILDFILE }}" }}
                if NOT "%%B%%C" == "%%C%%B" (
        echo ***************** echo Inserting %%B - %%C echo *****************
        echo         uses: SafetyNationalPublic/devops_sn-common/actions/build_workflow_library@main>> {{ "{{ inputs.BUILDFILE }}" }}
        echo         with:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo           BRANCH: ${{ github.event.inputs.BRANCH }}>> {{ "{{ inputs.BUILDFILE }}" }}
        echo           PROJECTPATH: ^"%%B\\%%C^">> {{ "{{ inputs.BUILDFILE }}" }}
        echo           PROJECTFILENAME: "%%B">> {{ "{{ inputs.BUILDFILE }}" }}
        echo           NUGET_API_KEY: {{ "${{ secrets.NUGET_API_KEY }}" }}>> {{ "{{ inputs.BUILDFILE }}" }}
                ) else (
        echo ***************** echo Inserting %%B only echo *****************
        echo         uses: SafetyNationalPublic/devops_sn-common/actions/build_workflow_library_if_exists@main>> {{ "{{ inputs.BUILDFILE }}" }}
        echo         with:>> {{ "{{ inputs.BUILDFILE }}" }}
        echo           BRANCH: ${{ github.event.inputs.BRANCH }}>> {{ "{{ inputs.BUILDFILE }}" }}
        echo           PROJECT: ^"%%B^">> {{ "{{ inputs.BUILDFILE }}" }}
        echo           NUGET_API_KEY: {{ "${{ secrets.NUGET_API_KEY }}" }}>> {{ "{{ inputs.BUILDFILE }}" }}
                )
            )
        )
        echo Build File Located at: {{ "{{ inputs.BUILDFILE }}" }}
        more {{ "{{ inputs.BUILDFILE }}" }}
