name: "Build Libraries"
inputs:
  BRANCH:
    description: 'Branch to build'
    default: 'master'
    required: true
    type: string
  BUILDFILE:
    required: true
    type: string
  SOLUTIONNAME:
    required: true
    type: string
  PROJECTS:
    required: true
    type: string

runs:
  using: "composite"
  steps: 
    - name: Make Dynamic Build Yaml Script
      shell: cmd
      run: |
        mkdir .github\actions\${{ inputs.BUILDFILE }}
        SET action=.github/actions/${{ inputs.BUILDFILE }}.yaml
        echo name: Build - {${{ inputs.SOLUTIONNAME }}  > %action%
        echo on:>>  %action%
        echo   workflow_dispatch:>>  %action%
        echo     inputs:>>  %action%
        echo       BRANCH:>>  %action%
        echo         description: 'Branch to build'>>  %action%
        echo         default: 'master'>>  %action%
        echo         required: true>>  %action%
        echo defaults:>>  %action%
        echo   run:>>  %action%
        echo     shell: cmd>>  %action%
        echo jobs:>>  %action%
        echo   Build_Libraries:>>  %action%
        echo     name: "Build Libraries">>  %action%
        echo     runs-on: SNGithubRunner>>  %action%
        echo     steps:>>  %action%
        echo       - name: "Call Checkout">>  %action%
        echo         uses: actions/checkout@v3>>  %action%
        echo         with:>>  %action%
        echo           ref: ${{ inputs.BRANCH }}>>  %action%

        for %%a in ${{ inputs.PROJECTS }} }}) do (
            for /F "tokens=1-2 delims=#" %%B in ("%%a") do (
        echo       - name: "Build %%B">>  %action%
                if NOT "%%B%%C" == "%%C%%B" (
        echo ***************** echo Inserting %%B - %%C echo *****************
        echo         uses: SafetyNationalPublic/devops_sn-common/actions/build_workflow_library@main>>  %action%
        echo         with:>>  %action%
        echo           BRANCH: ${{ inputs.BRANCH }}>>  %action%
        echo           PROJECTPATH: ^"%%B\\%%C^">>  %action%
        echo           PROJECTFILENAME: "%%B">>  %action%
        echo           NUGET_API_KEY: {{ $'{{ secrets.NUGET_API_KEY }}' }}>>  %action%
                ) else (
        echo ***************** echo Inserting %%B only echo *****************
        echo         uses: SafetyNationalPublic/devops_sn-common/actions/build_workflow_library_if_exists@main>>  %action%
        echo         with:>>  %action%
        echo           BRANCH: ${{ inputs.BRANCH }}>>  %action%
        echo           PROJECT: ^"%%B^">>  %action%
        echo           NUGET_API_KEY: {{ $'{{ secrets.NUGET_API_KEY }}' }}>>  %action%
                )
            )
        )
        echo Build File Located at:  %action%
        type  %action%
